### ISSUE TITLE
Overwrite if exists (or if newer)

### ISSUE THREAD

**Issue by JoshRiser** [mCzolko/grunt-downloadfile#6]
I am not sure if anyone is still working on this, but I am using this plugin at the moment to download the latest version of jQuery to use in my projects. When the file already exists it gives me an error. I would prefer to have an option to overwrite if it exists, or if possible an option to only overwrite if the file downloaded is never than the current one.

I think I would be able to figure out how to make it overwrite if it exists, but I don't know where to start to check if the file is newer.

**Comment by paumoreno** [comment]
+1

**Comment by ramaguduri** [comment]
+1
